"""fix_assets_columns

Revision ID: be13e82ede2b
Revises: ec2f0bf4472e
Create Date: 2026-05-18 11:58:11.356341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be13e82ede2b'
down_revision = 'ec2f0bf4472e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cryptos_symbol_key'), type_='unique')
        batch_op.drop_column('symbol')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stocks_ticker_key'), type_='unique')
        batch_op.drop_column('ticker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('stocks_ticker_key'), ['ticker'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('cryptos_symbol_key'), ['symbol'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
